const english = {
 leave: 'Discard your unsaved changes?', title: 'Member details', privacy: 'These private details do not appear on your general profile.', optional: 'All fields are optional.', familyName: 'Family name', givenName: 'Given name', gender: 'Gender', identityDocument: 'Taiwan ID number', mobile: 'Mobile number', unspecified: 'Not provided', male: 'Male', female: 'Female', other: 'Other', prefer_not_to_say: 'Prefer not to say', save: 'Save changes', remove: 'Delete details', confirm: 'Delete all your member details?', saved: 'Member details saved.', deleted: 'Member details deleted.', loading: 'Loading member details', failed: 'Unable to load member details.', invalid: 'Check the fields. Mobile numbers need an international country code.', conflict: 'The data changed. Reload before editing again.', uncertain: 'We could not confirm the result. Reload to check your details before making another change.', retry: 'Reload', back: 'Back to profile',
}
export const memberDetailsMessages = {
 en: english,
 'zh-Hant': { leave: '捨棄尚未儲存的變更？', title: '會員資料', privacy: '這些私人資料不會出現在一般個人資料頁。', optional: '所有欄位皆為選填。', familyName: '姓', givenName: '名', gender: '性別', identityDocument: '身分證字號', mobile: '手機', unspecified: '未提供', male: '男性', female: '女性', other: '其他', prefer_not_to_say: '不願透露', save: '儲存變更', remove: '刪除會員資料', confirm: '確定刪除所有會員資料？', saved: '會員資料已儲存。', deleted: '會員資料已刪除。', loading: '載入會員資料中', failed: '無法載入會員資料。', invalid: '請檢查欄位；手機需包含國際國碼。', conflict: '資料已變更，請重新載入後編輯。', uncertain: '無法確認操作結果。請重新載入，確認資料後再變更。', retry: '重新載入', back: '返回個人資料' },
 'zh-Hans': { leave: '放弃尚未保存的更改？', title: '会员资料', privacy: '这些私人资料不会出现在一般个人资料页。', optional: '所有字段均为选填。', familyName: '姓', givenName: '名', gender: '性别', identityDocument: '身份证号码', mobile: '手机', unspecified: '未提供', male: '男性', female: '女性', other: '其他', prefer_not_to_say: '不愿透露', save: '保存更改', remove: '删除会员资料', confirm: '确定删除所有会员资料？', saved: '会员资料已保存。', deleted: '会员资料已删除。', loading: '正在加载会员资料', failed: '无法加载会员资料。', invalid: '请检查字段；手机需包含国际区号。', conflict: '资料已更改，请重新加载后编辑。', uncertain: '无法确认操作结果。请重新加载，确认资料后再更改。', retry: '重新加载', back: '返回个人资料' },
 ja: { leave: '未保存の変更を破棄しますか？', title: '会員情報', privacy: 'この非公開情報は通常のプロフィールに表示されません。', optional: 'すべて任意項目です。', familyName: '姓', givenName: '名', gender: '性別', identityDocument: '台湾身分証番号', mobile: '携帯電話', unspecified: '未提供', male: '男性', female: '女性', other: 'その他', prefer_not_to_say: '回答しない', save: '変更を保存', remove: '会員情報を削除', confirm: '会員情報をすべて削除しますか？', saved: '保存しました。', deleted: '削除しました。', loading: '会員情報を読み込み中', failed: '会員情報を読み込めません。', invalid: '項目を確認してください。電話番号には国番号が必要です。', conflict: '情報が変更されました。再読み込みしてください。', uncertain: '結果を確認できません。変更する前に再読み込みしてください。', retry: '再読み込み', back: 'プロフィールに戻る' },
 ko: { leave: '저장하지 않은 변경을 버릴까요?', title: '회원 정보', privacy: '이 비공개 정보는 일반 프로필에 표시되지 않습니다.', optional: '모든 항목은 선택 사항입니다.', familyName: '성', givenName: '이름', gender: '성별', identityDocument: '대만 신분증 번호', mobile: '휴대전화', unspecified: '미제공', male: '남성', female: '여성', other: '기타', prefer_not_to_say: '응답하지 않음', save: '변경 저장', remove: '회원 정보 삭제', confirm: '회원 정보를 모두 삭제하시겠습니까?', saved: '저장되었습니다.', deleted: '삭제되었습니다.', loading: '회원 정보 로딩 중', failed: '회원 정보를 불러올 수 없습니다.', invalid: '항목을 확인하세요. 전화번호에는 국가 코드가 필요합니다.', conflict: '정보가 변경되었습니다. 다시 불러오세요.', uncertain: '결과를 확인할 수 없습니다. 변경 전에 다시 불러오세요.', retry: '다시 불러오기', back: '프로필로 돌아가기' },
}
