import type { Locale } from './locales'
const en = {
  title: 'Service roster', mine: 'My service', team: 'Fellowship roster', fellowship: 'Fellowship', month: 'Month', previous: 'Previous month', next: 'Next month', zone: 'Time zone', loading: 'Loading service roster', retry: 'Retry', failed: 'Unable to load the roster. Please try again.', empty: 'No service scheduled this month', noTeams: 'You have not joined a service fellowship', detail: 'Service details', close: 'Close', you: 'You', unassigned: 'To be assigned', cancelled: 'Cancelled', open: 'Seeking a substitute', invitation: 'Substitution invitation', helpPending: 'Leader assistance requested', attention: 'Eligibility changed. Please ask your leader to review this assignment.', overlap: 'This overlaps with another service assignment. Check the time before accepting.', request: 'Find a substitute', switch: 'Manage substitution', accept: 'Accept substitution', decline: 'Unable to substitute', withdraw: 'Withdraw request', help: 'Ask the leader for help', person: 'Invite a member', public: 'Ask the fellowship', peer: 'Member', search: 'Search members', noPeers: 'No matching members', submit: 'Send request', confirm: 'Confirm', pendingHint: 'You remain responsible until someone accepts.', acceptHint: 'After accepting, you will be responsible for this assignment.', done: 'Updated', commandFailed: 'The action could not be confirmed. Retry to check the result.', stale: 'This assignment has changed. Review the latest details before trying again.', unavailable: 'This assignment is no longer available.', refresh: 'Reload details', waiting: 'Waiting for a reply', notices: 'Notifications', preferences: 'Reminders', loadMore: 'Load more', noNotices: 'No service notifications', reminder: 'Service reminder', days: 'Days before', time: 'Reminder time', save: 'Save', saved: 'Saved', prefFailed: 'Unable to save reminder settings. Please try again.', prefStale: 'Reminder settings changed elsewhere. Reload before saving.', noLeaders: 'Your request is saved, but no fellowship leader can be notified.', declineStatus: 'The invited member cannot substitute', expired: 'The substitution request has ended', invalidated: 'The substitution request is no longer valid', reminderSkipped: 'No reminder is scheduled for this assignment.',
}
const zh: typeof en = {
  title: '服事表', mine: '我的服事', team: '團契班表', fellowship: '團契', month: '月份', previous: '上個月', next: '下個月', zone: '時區', loading: '載入服事表', retry: '重試', failed: '無法載入服事表，請重試。', empty: '這個月沒有服事安排', noTeams: '尚未加入服事團契', detail: '服事詳情', close: '關閉', you: '你', unassigned: '待安排', cancelled: '已取消', open: '正在向團契徵求代班', invitation: '代班邀請', helpPending: '負責人協助中', attention: '人選資格已變更，請負責人重新安排。', overlap: '與你的其他服事重疊，接受前請確認時間。', request: '找代班', switch: '管理代班', accept: '接受代班', decline: '無法代班', withdraw: '撤回代班請求', help: '請負責人協助', person: '邀請同工', public: '團契徵求', peer: '同工', search: '搜尋同工', noPeers: '沒有符合的同工', submit: '送出邀請', confirm: '確認', pendingHint: '對方接受前，仍由你服事。', acceptHint: '接受後，這次服事會改由你負責。', done: '已更新', commandFailed: '尚無法確認操作結果，請重試確認。', stale: '這項服事已更新，請查看最新內容後再操作。', unavailable: '這項服事已無法存取。', refresh: '重新載入詳情', waiting: '等待同工回覆', notices: '通知', preferences: '提醒設定', loadMore: '載入更多', noNotices: '目前沒有服事通知', reminder: '服事提醒', days: '提前天數', time: '提醒時間', save: '儲存', saved: '已儲存', prefFailed: '無法儲存提醒設定，請重試。', prefStale: '提醒設定已在其他地方更新，請重新載入。', noLeaders: '已保留求助，目前沒有可通知的團契負責人。', declineStatus: '對方這次無法代班', expired: '代班請求已截止', invalidated: '代班請求已失效', reminderSkipped: '這次沒有排定提醒。',
}
const hans: typeof en = { ...zh,
  title: '服事表', team: '团契班表', fellowship: '团契', previous: '上个月', next: '下个月', zone: '时区', loading: '载入服事表', retry: '重试', failed: '无法载入服事表，请重试。', empty: '这个月没有服事安排', noTeams: '尚未加入服事团契', detail: '服事详情', close: '关闭', cancelled: '已取消', open: '正在向团契征求代班', invitation: '代班邀请', helpPending: '负责人协助中', attention: '人选资格已变更，请负责人重新安排。', overlap: '与你的其他服事重叠，接受前请确认时间。', decline: '无法代班', withdraw: '撤回代班请求', help: '请负责人协助', person: '邀请同工', public: '团契征求', search: '搜索同工', noPeers: '没有符合的同工', submit: '送出邀请', confirm: '确认', pendingHint: '对方接受前，仍由你服事。', acceptHint: '接受后，这次服事会改由你负责。', commandFailed: '尚无法确认操作结果，请重试确认。', stale: '这项服事已更新，请查看最新内容后再操作。', unavailable: '这项服事已无法访问。', refresh: '重新载入详情', waiting: '等待同工回复', preferences: '提醒设置', loadMore: '载入更多', noNotices: '目前没有服事通知', days: '提前天数', time: '提醒时间', save: '保存', saved: '已保存', prefFailed: '无法保存提醒设置，请重试。', prefStale: '提醒设置已在其他地方更新，请重新载入。', noLeaders: '已保留求助，目前没有可通知的团契负责人。', declineStatus: '对方这次无法代班', expired: '代班请求已截止', invalidated: '代班请求已失效', reminderSkipped: '这次没有排定提醒。',
}
export const serviceMessages: Record<Locale, typeof en> = { en, 'zh-Hant': zh, 'zh-Hans': hans, ja: en, ko: en }
